"""AWS provider convenience functions for Archflow diagrams.

Auto-generated from archflow-icons registry manifest.
Usage:
    from archflow.providers.aws import EC2, RDS, Lambda, VPC, Region
"""

from archflow.cluster import Cluster
from archflow.node import Node

# ── Node definitions from aws manifest (307 icons) ──
_NODES = [
    "acm",
    "activate",
    "alexa-for-business",
    "amplify",
    "apache-mxnet-on-aws",
    "api-gateway",
    "app-mesh",
    "app-runner",
    "app-studio",
    "appconfig",
    "appfabric",
    "appflow",
    "application-auto-scaling",
    "application-discovery-service",
    "application-migration-service",
    "application-recovery-controller",
    "appstream-2",
    "appsync",
    "artifact",
    "athena",
    "audit-manager",
    "augmented-ai-a2i",
    "aurora",
    "auto-scaling",
    "b2b-data-interchange",
    "backint-agent",
    "backup",
    "batch",
    "bedrock",
    "billing-conductor",
    "bottlerocket",
    "braket",
    "budgets",
    "chatbot",
    "chime",
    "chime-sdk",
    "clean-rooms",
    "client-vpn",
    "cloud-control-api",
    "cloud-development-kit",
    "cloud-directory",
    "cloud-map",
    "cloud-wan",
    "cloud9",
    "cloudformation",
    "cloudfront",
    "cloudhsm",
    "cloudsearch",
    "cloudshell",
    "cloudtrail",
    "cloudwatch",
    "codeartifact",
    "codebuild",
    "codecatalyst",
    "codecommit",
    "codedeploy",
    "codeguru",
    "codepipeline",
    "codewhisperer",
    "cognito",
    "command-line-interface",
    "comprehend",
    "comprehend-medical",
    "compute-optimizer",
    "config",
    "connect",
    "console-mobile-application",
    "control-tower",
    "corretto",
    "cost-and-usage-report",
    "cost-explorer",
    "data-exchange",
    "data-firehose",
    "data-transfer-terminal",
    "datasync",
    "datazone",
    "dcv",
    "deadline-cloud",
    "deep-learning-amis",
    "deep-learning-containers",
    "deepcomposer",
    "deepracer",
    "detective",
    "device-farm",
    "devops-guru",
    "direct-connect",
    "directory-service",
    "distro-for-opentelemetry",
    "dms",
    "documentdb",
    "dynamodb",
    "ebs",
    "ec2",
    "ec2-auto-scaling",
    "ec2-image-builder",
    "ecr",
    "ecs",
    "ecs-anywhere",
    "efs",
    "eks",
    "eks-anywhere",
    "eks-cloud",
    "eks-distro",
    "elastic-beanstalk",
    "elastic-disaster-recovery",
    "elastic-fabric-adapter",
    "elastic-inference",
    "elastic-transcoder",
    "elastic-vmware-service",
    "elasticache",
    "elb",
    "elemental-appliances-&-software",
    "elemental-conductor",
    "elemental-delta",
    "elemental-link",
    "elemental-live",
    "elemental-mediaconnect",
    "elemental-mediaconvert",
    "elemental-medialive",
    "elemental-mediapackage",
    "elemental-mediastore",
    "elemental-mediatailor",
    "elemental-server",
    "emr",
    "end-user-messaging",
    "entity-resolution",
    "eventbridge",
    "express-workflows",
    "fargate",
    "fault-injection-service",
    "file-cache",
    "finspace",
    "firewall-manager",
    "forecast",
    "fraud-detector",
    "freertos",
    "fsx",
    "fsx-for-lustre",
    "fsx-for-netapp-ontap",
    "fsx-for-openzfs",
    "fsx-for-wfs",
    "gamelift-servers",
    "gamelift-streams",
    "global-accelerator",
    "glue",
    "glue-databrew",
    "ground-station",
    "guardduty",
    "health-dashboard",
    "healthimaging",
    "healthlake",
    "healthomics",
    "healthscribe",
    "iam",
    "iam-identity-center",
    "infrastructure-composer",
    "inspector",
    "interactive-video-service",
    "iot-analytics",
    "iot-button",
    "iot-core",
    "iot-device-defender",
    "iot-device-management",
    "iot-events",
    "iot-expresslink",
    "iot-fleetwise",
    "iot-greengrass",
    "iot-sitewise",
    "iot-twinmaker",
    "iq",
    "kendra",
    "keyspaces",
    "kinesis",
    "kinesis-data-streams",
    "kinesis-video-streams",
    "kms",
    "lake-formation",
    "lambda",
    "launch-wizard",
    "lex",
    "license-manager",
    "lightsail",
    "lightsail-for-research",
    "local-zones",
    "location-service",
    "lookout-for-equipment",
    "lookout-for-metrics",
    "lookout-for-vision",
    "macie",
    "mainframe-modernization",
    "managed-blockchain",
    "managed-grafana",
    "managed-service-for-apache-flink",
    "managed-service-for-prometheus",
    "managed-services",
    "managed-workflows-for-apache-airflow",
    "management-console",
    "marketplace_dark",
    "marketplace_light",
    "memorydb",
    "migration-evaluator",
    "migration-hub",
    "monitron",
    "mq",
    "msk",
    "neptune",
    "network-firewall",
    "neuron",
    "nice-enginframe",
    "nitro-enclaves",
    "nova",
    "open-3d-engine",
    "opensearch",
    "oracle-database-at-aws",
    "organizations",
    "outposts-family",
    "outposts-rack",
    "outposts-servers",
    "panorama",
    "parallel-cluster",
    "parallel-computing-service",
    "payment-cryptography",
    "personalize",
    "pinpoint",
    "pinpoint-apis",
    "polly",
    "private-5g",
    "private-certificate-authority",
    "privatelink",
    "professional-services",
    "proton",
    "pytorch-on-aws",
    "q",
    "quantum-ledger-database",
    "quicksight",
    "rds",
    "red-hat-openshift-service-on-aws",
    "redshift",
    "rekognition",
    "repost",
    "repost-private",
    "reserved-instance-reporting",
    "resilience-hub",
    "resource-access-manager",
    "resource-explorer",
    "route53",
    "s3",
    "s3-glacier",
    "s3-on-outposts",
    "sagemaker",
    "sagemaker-ai",
    "sagemaker-ground-truth",
    "sagemaker-studio-lab",
    "sar",
    "savings-plans",
    "secrets-manager",
    "security-hub",
    "security-incident-response",
    "security-lake",
    "service-catalog",
    "service-management-connector",
    "shield",
    "signer",
    "simple-email-service",
    "simspace-weaver",
    "site-to-site-vpn",
    "snowball",
    "snowball-edge",
    "sns",
    "sqs",
    "step-functions",
    "storage-gateway",
    "supply-chain",
    "support",
    "systems-manager",
    "telco-network-builder",
    "tensorflow-on-aws",
    "textract",
    "thinkbox-deadline",
    "thinkbox-frost",
    "thinkbox-krakatoa",
    "thinkbox-sequoia",
    "thinkbox-stoke",
    "thinkbox-xmesh",
    "timestream",
    "tools-and-sdks",
    "training-certification",
    "transcribe",
    "transfer-family",
    "transform",
    "transit-gateway",
    "translate",
    "trusted-advisor",
    "user-notifications",
    "verified-access",
    "verified-permissions",
    "vpc",
    "vpc-lattice",
    "waf",
    "wavelength",
    "well-architected-tool",
    "wickr",
    "workdocs",
    "workdocs-sdk",
    "workmail",
    "workspaces-family",
    "xray",
]

# ── Cluster types ──
_CLUSTERS = {
    "region": "region",
    "vpc": "vpc",
    "subnet": "subnet",
    "private-subnet": "subnet",
    "public-subnet": "subnet",
    "auto-scaling-group": "auto-scaling-group",
    "account": "account",
}


def _icon_to_func_name(icon: str) -> str:
    """Convert icon name to PascalCase function name.

    ec2 → EC2, api-gateway → ApiGateway, s3-glacier → S3Glacier
    """
    # Special cases for acronyms
    _UPPER = {
        "ec2",
        "rds",
        "s3",
        "elb",
        "ebs",
        "efs",
        "ecs",
        "eks",
        "ecr",
        "emr",
        "sqs",
        "sns",
        "iam",
        "acm",
        "kms",
        "mq",
        "msk",
        "waf",
        "dms",
        "dcv",
        "iq",
        "q",
        "vpc",
        "dns",
    }
    parts = icon.replace("_", "-").split("-")
    result = []
    for part in parts:
        if part in _UPPER:
            result.append(part.upper())
        elif part and part[0].isdigit():
            result.append(part)
        else:
            result.append(part.capitalize())
    return "".join(result)


def _make_node_func(icon_name: str):
    """Create a node factory function for a given icon."""
    func_name = _icon_to_func_name(icon_name)
    default_label = func_name

    def factory(label: str = default_label, **style):
        node_id = label.lower().replace(" ", "_")
        return Node(node_id, label, provider="aws", icon=icon_name, **style)

    factory.__name__ = func_name
    factory.__qualname__ = func_name
    factory.__doc__ = f"Create an AWS {func_name} node."
    return func_name, factory


def _make_cluster_func(name: str, cluster_type: str):
    """Create a cluster factory function."""
    func_name = _icon_to_func_name(name)
    default_label = func_name

    def factory(label: str = default_label, **style):
        cluster_id = label.lower().replace(" ", "_")
        return Cluster(cluster_id, label, provider="aws", cluster_type=cluster_type, **style)

    factory.__name__ = func_name
    factory.__qualname__ = func_name
    factory.__doc__ = f"Create an AWS {func_name} cluster."
    return func_name, factory


# ── Dynamically create all functions ──
__all__ = []

for _icon in _NODES:
    _name, _func = _make_node_func(_icon)
    globals()[_name] = _func
    __all__.append(_name)

for _cname, _ctype in _CLUSTERS.items():
    _name, _func = _make_cluster_func(_cname, _ctype)
    if _name not in globals():  # don't override node funcs
        globals()[_name] = _func
        __all__.append(_name)
